import { StyleSheet } from 'react-native';

import { MIN_OVERVIEW_ROW_WIDTH } from '../constants';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#eef5fb',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: 16,
    gap: 16,
  },
  statisticsPage: {
    gap: 16,
    paddingBottom: 4,
  },
  header: {
    gap: 8,
    paddingTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  headerTextGroup: {
    flex: 1,
    gap: 8,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#12304a',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 22,
    color: '#415a73',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    gap: 14,
    shadowColor: '#12304a',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#12304a',
  },
  fieldGroup: {
    gap: 8,
  },
  fieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fieldLabelGroup: {
    flex: 1,
    gap: 2,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#12304a',
  },
  fieldPrompt: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1f4668',
  },
  input: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#f9fbfd',
    fontSize: 15,
    lineHeight: 21,
    color: '#17324b',
  },
  metaFieldsCard: {
    gap: 10,
  },
  metaInput: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f9fbfd',
    fontSize: 15,
    color: '#17324b',
  },
  metaDateButton: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f9fbfd',
  },
  metaDateButtonText: {
    fontSize: 15,
    color: '#17324b',
    fontWeight: '600',
  },
  pickerDoneButton: {
    alignSelf: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  pickerDoneButtonText: {
    fontSize: 16,
    color: '#0f6cbd',
    fontWeight: '700',
  },
  error: {
    color: '#b42318',
    fontWeight: '600',
  },
  storageMessage: {
    color: '#9a6700',
    fontWeight: '600',
  },
  button: {
    backgroundColor: '#0f6cbd',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  buttonPressed: {
    opacity: 0.85,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badge: {
    minWidth: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    textAlign: 'center',
    backgroundColor: '#dbeafe',
    color: '#0f4c81',
    fontWeight: '700',
  },
  emptyState: {
    fontSize: 15,
    lineHeight: 22,
    color: '#587086',
  },
  emptyStateGroup: {
    gap: 14,
  },
  entryCard: {
    borderWidth: 1,
    borderColor: '#d6e2ee',
    borderRadius: 14,
    padding: 14,
    gap: 10,
    backgroundColor: '#f9fbfd',
  },
  entryDate: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f4668',
  },
  entryTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  entryOverviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: MIN_OVERVIEW_ROW_WIDTH,
  },
  entryLocation: {
    fontSize: 14,
    color: '#415a73',
    flexShrink: 1,
  },
  linkButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#95c6ef',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#edf6ff',
  },
  linkButtonText: {
    color: '#0f4c81',
    fontSize: 14,
    fontWeight: '700',
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 999,
    backgroundColor: '#0f6cbd',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  iconButtonText: {
    color: '#ffffff',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '700',
  },
  secondaryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  secondaryButtonText: {
    color: '#1f4668',
    fontSize: 16,
    fontWeight: '700',
  },
  pageSwitch: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#dbe7f3',
    borderRadius: 999,
    padding: 6,
  },
  pageSwitchButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: 'center',
  },
  pageSwitchButtonActive: {
    backgroundColor: '#ffffff',
  },
  pageSwitchButtonText: {
    color: '#51677d',
    fontSize: 15,
    fontWeight: '700',
  },
  pageSwitchButtonTextActive: {
    color: '#12304a',
  },
  editButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
  },
  editButtonText: {
    color: '#1f4668',
    fontSize: 14,
    fontWeight: '700',
  },
  deleteButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#f5c6cb',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#fff5f5',
  },
  deleteButtonText: {
    color: '#b42318',
    fontSize: 14,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(18, 48, 74, 0.45)',
    justifyContent: 'flex-end',
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    maxHeight: '92%',
    backgroundColor: '#eef5fb',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 24,
    gap: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dbeafe',
  },
  closeButtonText: {
    color: '#12304a',
    fontSize: 20,
    fontWeight: '700',
  },
  modalContent: {
    gap: 14,
    paddingBottom: 12,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 12,
  },
  dialogPrimaryButton: {
    flex: 1,
  },
  handIcon: {
    width: 48,
    height: 52,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  handFingers: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 3,
    marginBottom: 2,
  },
  handFinger: {
    width: 7,
    borderRadius: 999,
  },
  handLittleFinger: {
    height: 18,
  },
  handRingFinger: {
    height: 24,
  },
  handMiddleFinger: {
    height: 28,
  },
  handIndexFinger: {
    height: 26,
  },
  handFingerClosed: {
    height: 8,
  },
  handBase: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  handThumb: {
    width: 8,
    height: 20,
    borderRadius: 999,
    transform: [{ rotate: '45deg' }],
    marginLeft: -5,
    marginBottom: 2,
  },
  handThumbClosed: {
    height: 10,
  },
  handPalm: {
    width: 28,
    height: 20,
    borderRadius: 10,
  },
  handPartActive: {
    backgroundColor: '#12304a',
  },
  handPartInactive: {
    backgroundColor: '#bfd2e6',
  },
  locationPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationPickerText: {
    flex: 1,
    fontSize: 15,
    color: '#17324b',
  },
  locationPickerPlaceholder: {
    color: '#7a8da3',
  },
  locationPickerIcon: {
    fontSize: 18,
    marginLeft: 8,
  },
  locationPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#c7d7e7',
  },
  categoryChipsContainer: {
    marginTop: 2,
  },
  categoryChipsScroll: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 2,
  },
  categoryChip: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f9fbfd',
  },
  categoryChipSelected: {
    backgroundColor: '#0f6cbd',
    borderColor: '#0f6cbd',
  },
  categoryChipText: {
    fontSize: 13,
    color: '#1f4668',
    fontWeight: '500',
  },
  categoryChipTextSelected: {
    color: '#ffffff',
    fontWeight: '700',
  },
  statisticsIntro: {
    fontSize: 15,
    lineHeight: 22,
    color: '#415a73',
  },
  statisticsFilterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  filterTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#12304a',
  },
  filterChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f9fbfd',
  },
  filterChipSelected: {
    borderColor: '#0f6cbd',
    backgroundColor: '#0f6cbd',
  },
  filterChipText: {
    fontSize: 13,
    color: '#1f4668',
    fontWeight: '600',
  },
  filterChipTextSelected: {
    color: '#ffffff',
  },
  resetFilterText: {
    color: '#0f6cbd',
    fontSize: 14,
    fontWeight: '700',
  },
  summaryGrid: {
    gap: 12,
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    gap: 8,
    shadowColor: '#12304a',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#587086',
    fontWeight: '600',
  },
  summaryValue: {
    fontSize: 28,
    color: '#12304a',
    fontWeight: '700',
  },
  summaryValueSmall: {
    fontSize: 22,
    color: '#12304a',
    fontWeight: '700',
  },
  statisticsCardHeader: {
    gap: 4,
  },
  statisticsCaption: {
    fontSize: 14,
    color: '#587086',
  },
  spiderCard: {
    gap: 16,
    alignItems: 'center',
  },
  spiderChart: {
    width: 240,
    height: 240,
    alignSelf: 'center',
    position: 'relative',
  },
  spiderScaleRing: {
    position: 'absolute',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(87, 112, 134, 0.2)',
  },
  spiderScaleLabel: {
    position: 'absolute',
    right: 2,
    fontSize: 11,
    color: '#587086',
    fontWeight: '600',
  },
  spiderRingSegment: {
    position: 'absolute',
    borderRadius: 999,
  },
  spiderGroupPill: {
    position: 'absolute',
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  spiderGroupPillLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
  },
  spiderAxis: {
    position: 'absolute',
    width: 78,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#d6e2ee',
  },
  spiderLine: {
    position: 'absolute',
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(87, 112, 134, 0.4)',
  },
  spiderPoint: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: '#0f6cbd',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  spiderPointSelected: {
    borderColor: '#12304a',
    borderWidth: 3,
    transform: [{ scale: 1.2 }],
    zIndex: 2,
  },
  spiderOuterDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  spiderGroupLegend: {
    width: '100%',
    gap: 8,
  },
  spiderGroupLegendTitle: {
    fontSize: 12,
    color: '#587086',
    fontWeight: '700',
  },
  spiderGroupRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  spiderGroupChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#f2f7fc',
    borderWidth: 1,
    borderColor: '#d6e2ee',
  },
  spiderGroupColor: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  spiderGroupText: {
    fontSize: 12,
    color: '#415a73',
    fontWeight: '600',
  },
  spiderSelection: {
    width: '100%',
    fontSize: 13,
    fontWeight: '700',
    color: '#12304a',
  },
  spiderSelectionHint: {
    width: '100%',
    fontSize: 13,
    color: '#587086',
  },
  spiderLegend: {
    width: '100%',
    gap: 8,
  },
  spiderLegendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  spiderLegendRowSelected: {
    borderRadius: 10,
    backgroundColor: '#eef5fc',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  spiderLegendLabelGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  spiderLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  spiderLegendTextWrap: {
    flex: 1,
    gap: 2,
  },
  spiderLegendLabel: {
    fontSize: 14,
    color: '#415a73',
  },
  spiderLegendMeta: {
    fontSize: 12,
    color: '#587086',
  },
  spiderLegendValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#12304a',
  },
  monthChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
    minHeight: 150,
  },
  monthBarGroup: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  monthValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#12304a',
  },
  monthBar: {
    width: '100%',
    maxWidth: 40,
    borderRadius: 12,
    backgroundColor: '#0f6cbd',
  },
  monthLabel: {
    fontSize: 12,
    color: '#587086',
    fontWeight: '600',
  },
  phaseChart: {
    gap: 12,
  },
  phaseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  phaseLabel: {
    width: 92,
    fontSize: 13,
    color: '#415a73',
    fontWeight: '600',
  },
  phaseTrack: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    backgroundColor: '#e7eff7',
    overflow: 'hidden',
  },
  phaseFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#52a3e6',
  },
  phaseValue: {
    width: 24,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#12304a',
  },
  topCategoryList: {
    gap: 12,
  },
  topCategoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#d6e2ee',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#f9fbfd',
  },
  topCategoryTextGroup: {
    flex: 1,
    gap: 4,
  },
  topCategoryLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#12304a',
  },
  topCategoryMeta: {
    fontSize: 12,
    color: '#587086',
  },
  topCategoryCount: {
    minWidth: 32,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: '#0f6cbd',
  },
  statisticsFooter: {
    fontSize: 13,
    color: '#587086',
    fontWeight: '600',
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  crosshairOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crosshairVertical: {
    position: 'absolute',
    width: 2,
    height: 40,
    backgroundColor: '#e53e3e',
    borderRadius: 1,
  },
  crosshairHorizontal: {
    position: 'absolute',
    width: 40,
    height: 2,
    backgroundColor: '#e53e3e',
    borderRadius: 1,
  },
  locationPickerFooter: {
    padding: 16,
    paddingBottom: 24,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#c7d7e7',
    backgroundColor: '#eef5fb',
  },
  coordsText: {
    fontSize: 13,
    color: '#415a73',
    textAlign: 'center',
  },
});
