import { StyleSheet } from 'react-native';

import { MIN_OVERVIEW_ROW_WIDTH } from '../constants';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#eef5fb',
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: 16,
    gap: 16,
  },
  header: {
    gap: 8,
    paddingTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  headerTextGroup: {
    flex: 1,
    gap: 8,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#12304a',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 22,
    color: '#415a73',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    gap: 14,
    shadowColor: '#12304a',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#12304a',
  },
  fieldGroup: {
    gap: 8,
  },
  fieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fieldLabelGroup: {
    flex: 1,
    gap: 2,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#12304a',
  },
  fieldPrompt: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1f4668',
  },
  input: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#f9fbfd',
    fontSize: 15,
    lineHeight: 21,
    color: '#17324b',
  },
  metaFieldsCard: {
    gap: 10,
  },
  metaInput: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f9fbfd',
    fontSize: 15,
    color: '#17324b',
  },
  metaDateButton: {
    borderWidth: 1,
    borderColor: '#c7d7e7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f9fbfd',
  },
  metaDateButtonText: {
    fontSize: 15,
    color: '#17324b',
    fontWeight: '600',
  },
  pickerDoneButton: {
    alignSelf: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  pickerDoneButtonText: {
    fontSize: 16,
    color: '#0f6cbd',
    fontWeight: '700',
  },
  error: {
    color: '#b42318',
    fontWeight: '600',
  },
  storageMessage: {
    color: '#9a6700',
    fontWeight: '600',
  },
  button: {
    backgroundColor: '#0f6cbd',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  buttonPressed: {
    opacity: 0.85,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badge: {
    minWidth: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    textAlign: 'center',
    backgroundColor: '#dbeafe',
    color: '#0f4c81',
    fontWeight: '700',
  },
  emptyState: {
    fontSize: 15,
    lineHeight: 22,
    color: '#587086',
  },
  emptyStateGroup: {
    gap: 14,
  },
  entryCard: {
    borderWidth: 1,
    borderColor: '#d6e2ee',
    borderRadius: 14,
    padding: 14,
    gap: 10,
    backgroundColor: '#f9fbfd',
  },
  entryDate: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f4668',
  },
  entryTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  entryOverviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: MIN_OVERVIEW_ROW_WIDTH,
  },
  entryLocation: {
    fontSize: 14,
    color: '#415a73',
    flexShrink: 1,
  },
  linkButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#95c6ef',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#edf6ff',
  },
  linkButtonText: {
    color: '#0f4c81',
    fontSize: 14,
    fontWeight: '700',
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 999,
    backgroundColor: '#0f6cbd',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  iconButtonText: {
    color: '#ffffff',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '700',
  },
  secondaryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  secondaryButtonText: {
    color: '#1f4668',
    fontSize: 16,
    fontWeight: '700',
  },
  editButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#c7d7e7',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
  },
  editButtonText: {
    color: '#1f4668',
    fontSize: 14,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(18, 48, 74, 0.45)',
    justifyContent: 'flex-end',
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    maxHeight: '92%',
    backgroundColor: '#eef5fb',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 24,
    gap: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dbeafe',
  },
  closeButtonText: {
    color: '#12304a',
    fontSize: 20,
    fontWeight: '700',
  },
  modalContent: {
    gap: 14,
    paddingBottom: 12,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 12,
  },
  dialogPrimaryButton: {
    flex: 1,
  },
  handIcon: {
    width: 48,
    height: 52,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  handFingers: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 3,
    marginBottom: 2,
  },
  handFinger: {
    width: 7,
    borderRadius: 999,
  },
  handLittleFinger: {
    height: 18,
  },
  handRingFinger: {
    height: 24,
  },
  handMiddleFinger: {
    height: 28,
  },
  handIndexFinger: {
    height: 26,
  },
  handFingerClosed: {
    height: 8,
  },
  handBase: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  handThumb: {
    width: 8,
    height: 20,
    borderRadius: 999,
    transform: [{ rotate: '45deg' }],
    marginLeft: -5,
    marginBottom: 2,
  },
  handThumbClosed: {
    height: 10,
  },
  handPalm: {
    width: 28,
    height: 20,
    borderRadius: 10,
  },
  handPartActive: {
    backgroundColor: '#12304a',
  },
  handPartInactive: {
    backgroundColor: '#bfd2e6',
  },
  locationPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationPickerText: {
    flex: 1,
    fontSize: 15,
    color: '#17324b',
  },
  locationPickerPlaceholder: {
    color: '#7a8da3',
  },
  locationPickerIcon: {
    fontSize: 18,
    marginLeft: 8,
  },
  locationPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#c7d7e7',
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  crosshairOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crosshairVertical: {
    position: 'absolute',
    width: 2,
    height: 40,
    backgroundColor: '#e53e3e',
    borderRadius: 1,
  },
  crosshairHorizontal: {
    position: 'absolute',
    width: 40,
    height: 2,
    backgroundColor: '#e53e3e',
    borderRadius: 1,
  },
  locationPickerFooter: {
    padding: 16,
    paddingBottom: 24,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#c7d7e7',
    backgroundColor: '#eef5fb',
  },
  coordsText: {
    fontSize: 13,
    color: '#415a73',
    textAlign: 'center',
  },
});
